Onion.WEB/ViewModels/BranchViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OnionArhitectura.ViewModels;

public class BranchViewModel
{
    [Required(ErrorMessage = "Поле обязательно к заполнению")]
    public string Name { get; set; }
    [Required(ErrorMessage = "Поле обязательно к заполнению")]
    public string Location { get; set; }
}

Onion.WEB/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using Onion.Application.Interfaces;
using Onion.Domain.Entities;
using OnionArhitectura.ViewModels;

namespace OnionArhitectura.Controllers;

public class BranchController : Controller
{
    private readonly IBranchService _branchService;

    public BranchController(IBranchService branchService)
    {
        _branchService = branchService;
    }

    public async Task<IActionResult> AllBranches()
    {
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> CreateBranch()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateBranch(BranchViewModel model)
    {
        if (ModelState.IsValid)
        {
            Branch branch = new Branch()
            {
                Name = model.Name,
                Location = model.Location
            };
            await _branchService.AddBranchAsync(branch);
            return RedirectToAction("AllBranches");
        }
        return View(model);
    }


    [HttpGet]
    public async Task<IActionResult> Remove(int id)
    {
        if (id == 0)
        {
            return NotFound();
        }
        Branch branch = await _branchService.GetBranchByIdAsync(id);
        if (branch == null)
        {
            return NotFound();
        }
        return View(branch);
    }

    [HttpPost]
    public async Task<IActionResult> RemoveBranch(int id)
    {
        Branch branch = await _branchService.GetBranchByIdAsync(id);

        if (branch == null)
        {
            return NotFound();
        }
        await _branchService.RemoveBranchAsync(branch);
        return RedirectToAction("AllBranches");
    }
}

Onion.WEB/Views/Branch/AllBranches.cshtml
@using Onion.Domain.Entities
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Server.Kestrel.Core
@model IEnumerable<Onion.Domain.Entities.Branch>

@{
    ViewData["Title"] = "Филиалы";
}

<div class="d-flex justify-content-end mb-3">
    <button class="btn btn-dark" id="addBranchBtn" data-bs-toggle="modal" data-bs-target="#branchModal">
        <i class="fa-solid fa-plus"></i> Создать новый филиал
    </button>
</div>
<div class="mt-3">
    @if (Model != null && Model.Any())
    {
        <table id="branch-table" class="display" style="width: 100%;">
            <thead class="bg-dark">
            <tr>
                <th class="text-white">Название</th>
                <th class="text-white">Адрес</th>
                <th class="monday-school-color-blue">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach (Branch b in Model)
            {
                <tr>
                    <td>@b.Name</td>
                    <td>@b.Location</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary btn-sm dropdown-toggle" type="button" id="actionDropdown-@b.Id" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-bars"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <button class="dropdown-item editBranchBtn" data-bs-toggle="modal" data-bs-target="#branchModal"
                                            data-id="@b.Id"
                                            data-name="@b.Name"
                                            data-location="@b.Location">
                                        <i class="fa-solid fa-pen-to-square me-2"></i> Редактировать
                                    </button>
                                </li>
                                @if (User.IsInRole("director"))
                                {
                                    <li>
                                        <button class="dropdown-item text-danger deleteBranchButton" type="button" data-bs-toggle="modal" data-bs-target="#deleteBranchModal"
                                                data-id="@b.Id" data-location="@b.Location">
                                            <i class="fa-solid fa-trash me-2"></i> Удалить
                                        </button>
                                    </li>
                                }
                            </ul>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <h2 class="mt-3 text-center">В данный момент филиалов нет.</h2>
    }
</div>

<div class="modal fade" id="deleteBranchModal" tabindex="-1" aria-labelledby="deleteBranchModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark border-0">
                <h5 class="modal-title monday-school-color-gradient" id="deleteBranchModalLabel">Подтверждение удаления</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="deleteBranchForm" asp-action="RemoveBranch" method="post" asp-controller="Branch">
                <div class="modal-body bg-dark border-0">
                    <p class="text-white">Вы точно хотите удалить этот филиал по этому адресу?</p>
                    <p class="text-white" id="branchLocation"></p>
                    <p class="text-white">Действия необратимо!</p>
                    <input type="hidden" id="deleteBranchId" name="id" />
                </div>
                <div class="modal-footer bg-dark border-0">
                    <button type="submit" class="btn btn-outline-light fw-bold">
                        <i class="fa-solid fa-trash-can"></i> Удалить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="branchModal" tabindex="-1" aria-labelledby="branchModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-dark border-0">
                <h5 class="modal-title monday-school-color-gradient" id="branchModalLabel">Создание нового филиала</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body bg-dark border-0">
                <form id="branchForm">
                    <input type="hidden" name="Id" id="branchId" />
                    <div class="mb-3">
                        <input type="text" id="branchName" class="form-control" placeholder="Введите название филиала" />
                        <div id="nameError" class="text-danger mt-2" style="display: none"></div>
                    </div>
                    <div class="mb-3">
                        <input type="text" id="BranchLocation" class="form-control" placeholder="Введите адрес филиала" />
                        <div id="locationError" class="text-danger mt-2" style="display: none"></div>
                    </div>
                    <div class="modal-footer border-0">
                        <button type="submit" id="saveBranchBtn" class="btn btn-outline-light fw-bold">
                            <i class="fa-solid fa-check"></i> Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        
         $(document).ready(function() {
            $('#branch-table').DataTable({
                destroy: true,
                language: {
                    lengthMenu: "Показать _MENU_ записей",
                    search: "Поиск:",
                    info: "Показано _START_ до _END_ из _TOTAL_ записей",
                    infoFiltered: "(отфильтровано из _MAX_ записей)",
                    infoEmpty: "Не найдено подходящих записей",
                    zeroRecords: "Нет записей",
                    emptyTable: "Нет данных для отображения"
                },
                columnDefs: [
                    {
                        targets: 2,
                        width: '50px',
                        searchable: false,
                        orderable: false
                    }
                ],
                responsive: true
            });
            
            const minLength = 3;
            const modal = $('#branchModal');
            const form = $('#branchForm');
            const saveButton = $('#saveBranchBtn');
            const nameInput = $('#branchName');
            const locationInput = $('#BranchLocation');
            const nameError = $('#nameError');
            const locationError = $('#locationError');
            
            let isEditMode = false;  // Флаг для определения режима (создание/ редактирование)
            
            // Открытие модального окна для создания филиала
            
            $('#addBranchButton').on('click', function () {
                isEditMode = false;
                modal.find('#branchModalLabel').text('Создание нового филиала');
                saveButton.text('Создать');
                form[0].reset();
                nameError.hide();
                locationError.hide();
            });
            
            // Открытие модального окна для редактирования филиала
            $(document).on('click', '.editBranchBtn', function () {
                isEditMode = true;
                const branchId = $(this).data('id');
                const branchName = $(this).data('name');
                const branchLocation = $(this).data('location');
                
                modal.find('#branchModalLabel').text('Редактирование филиала');
                saveButton.text('Сохранить');
                $('#branchId').val(branchId);
                nameInput.val(branchName);
                locationInput.val(branchLocation);
                nameError.hide();
                locationError.hide();
            });
            
            // Обработка отправки формы
            form.submit(function (event) {
                event.preventDefault();
                
                const branchId = $('#branchId').val();
                const branchName = nameInput.val().trim();
                const branchLocation = locationInput.val().trim();
                let isValid = true;
                
                nameError.hide();
                locationError.hide();
                
                if (branchName.length < minLength){
                    nameError.text("Название филиала должно содержать не менее 3 символов.").show();
                    isValid = false;
                }
                
                if (branchLocation.length < minLength){
                    locationError.text("Адрес филиала должен содержать не менее 3 символов.").show();
                    isValid = false;
                }
                
                if (branchName === branchLocation){
                    locationError.text("Название и адрес не могут быть одинаковыми.").show();
                    isValid = false;
                }
                
                if (isValid){
                    const url = isEditMode
                        ? '@Url.Action("EditBranch", "Branch")'
                        : '@Url.Action("CreateBranch", "Branch")'
                        
                    const branchData = isEditMode
                        ? {
                          Id: branchId,
                          Name: branchName,
                          Location: branchLocation      
                        }
                    : {
                        Name: branchName,
                        Location: branchLocation
                      };
                      
                    $.ajax({
                        url: url,
                        type: 'POST',
                        headers: {
                            'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val()
                        },
                        contentType : 'application/json',
                        data: JSON.stringify(branchData),
                        success: function (response){
                            if (response.success) {
                                modal.modal('hide');
                                window.location.reload();
                            } else {
                                console.error("Ошибка:", response.message);
                            }
                        },
                        error: function (error){
                            console.error("Ошибка AJAX-запроса:", error);
                        }
                    });
                }
            });
            $('.deleteBranchButton').on('click', function () {
                let branchId = $(this).data('id');
                let branchLocation = $(this).data('location');
                
                $('#deleteBranchId').val(branchId);
                $('#branchLocation').text(branchLocation);
            });
         });
    </script>
    
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}