Onion.WEB/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Onion.Application.Interfaces;
using Onion.Domain.Entities;
using OnionArhitectura.ViewModels;

namespace OnionArhitectura.Controllers;

public class StudentController : Controller
{
    private readonly IStudentService _studentService;

    public StudentController(IStudentService studentService)
    {
        _studentService = studentService;
    }

    public async Task<IActionResult> AllStudents()
    {
        return View(await _studentService.GetAllStudentsAsync());
    }

    [HttpGet]
    public IActionResult CreateStudent()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateStudent(StudentViewModel model)
    {
        if (ModelState.IsValid)
        {
            Student student = new Student()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Phone = model.Phone,
                GroupId = model.GroupId,
                Description = model.Description,
                StudentType = true
            };
            await _studentService.AddStudentAsync(student);
            return RedirectToAction("AllStudents");
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult RemoveStudent()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveStudent(int id)
    {
        if (id == 0)
        {
            return NotFound();
        }

        Student student = await _studentService.GetStudentByIdAsync(id);

        if (student == null)
        {
            return NotFound();
        }

        await _studentService.RemoveStudentAsync(student);
        return RedirectToAction("AllStudents");
    }

    [HttpGet]
    public async Task<IActionResult> EditStudent(int id)
    {
        if (id == 0)
        {
            return NotFound();
        }

        Student student = await _studentService.GetStudentByIdAsync(id);
        if (student == null)
        {
            return NotFound();
        }

        StudentViewModel model = new StudentViewModel()
        {
            FirstName = student.FirstName,
            LastName = student.LastName,
            Description = student.Description,
            Phone = student.Phone,
            GroupId = student.GroupId,
        };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> EditStudent(StudentViewModel model, int id)
    {
        if (id == 0)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            Student student = await _studentService.GetStudentByIdAsync(id);
            student.FirstName = model.FirstName;
            student.LastName = model.LastName;
            student.Description = model.Description;
            student.Phone = model.Phone;
            student.GroupId = model.GroupId;
            await _studentService.UpdateStudentAsync(student);
            return RedirectToAction("AllStudents");
        }
        return View(model);
    }
}

Onion.WEB/Controllers/TeacherController.cs
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using Onion.Application.Interfaces;
using Onion.Domain.Entities;
using OnionArhitectura.ViewModels;

namespace OnionArhitectura.Controllers;

public class TeacherController : Controller
{
    private readonly ITeacherService _teacherService;

    public TeacherController(ITeacherService teacherService)
    {
        _teacherService = teacherService;
    }

    public async Task<IActionResult> AllTeachers()
    {
        var teachers = await _teacherService.GetTeachersAsync();

        var model = teachers.Select(t => new TeacherViewModel
        {
            Id = t.Id,
            FirstName = t.FirstName,
            LastName = t.LastName,
            LessonNameId = t.LessonNameId,
            BranchId = t.BranchId,
        });
        
        return View(model);
    }

    public async Task<IActionResult> AddTeacher()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddTeacher(TeacherViewModel model)
    {
        if (ModelState.IsValid)
        {
            Teacher teacher = new Teacher()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                BranchId = model.BranchId,
                LessonNameId = model.LessonNameId,
            };
            await _teacherService.AddTeacherAsync(teacher);
            return RedirectToAction("AllTeachers");
        }
        return View(model);
    }

    public async Task<IActionResult> DeleteTeacher(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Teacher teacher = await _teacherService.GetTeacherByIdAsync(id.Value);
        if (teacher == null)
        {
            return NotFound();
        }

        return View(teacher);
    }

    [HttpPost, ActionName("DeleteTeacher")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteTeacherConfirmed(int? id)
    {
        Teacher teacher = await _teacherService.GetTeacherByIdAsync(id.Value);
        if (teacher != null)
        {
            await _teacherService.DeleteTeacherAsync(teacher);
        }

        return RedirectToAction("AllTeachers");
    }

    public async Task<IActionResult> EditTeacher(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        
        Teacher teacher = await _teacherService.GetTeacherByIdAsync(id.Value);
        if (teacher == null)
        {
            return NotFound();
        }

        EditTeacherViewModel model = new EditTeacherViewModel()
        {
            Id = teacher.Id,
            FirstName = teacher.FirstName,
            LastName = teacher.LastName,
            BranchId = teacher.BranchId,
            LessonNameId = teacher.LessonNameId,
        };
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditTeacher(EditTeacherViewModel model)
    {
        if (ModelState.IsValid)
        {
            Teacher teacher = await _teacherService.GetTeacherByIdAsync(model.Id);
            if (teacher == null)
            {
                return NotFound();
            }
            
            teacher.FirstName = model.FirstName;
            teacher.LastName = model.LastName;
            teacher.BranchId = model.BranchId;
            teacher.LessonNameId = model.LessonNameId;
            await _teacherService.UpdateTeacherAsync(teacher);
            return RedirectToAction("AllTeachers");
        }

        return View(model);
    }
}

Onion.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Onion.WEB</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.1/css/dataTables.dataTables.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Onion.WEB.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.1/css/dataTables.dataTables.css" />
    <script src="https://kit.fontawesome.com/34932d7774.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand monday-school-color-gradient ms-2" asp-area="" asp-controller="Teacher" asp-action="AllTeachers">Teacher</a>
            <a class="navbar-brand monday-school-color-gradient ms-2" asp-area="" asp-controller="Student" asp-action="AllStudents">Student</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="AddTeacher">Добавить учителя</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="CreateStudent">Добавить студента</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
       
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.datatables.net/2.2.1/js/dataTables.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>